version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosec
    - ineffassign
    - misspell
    - gocritic
    - revive

linter-settings:
  goimports:
    local-prefixes: go-starter

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
